version: "3"

services:
  dynamodb:
    build:
      context: .
      dockerfile: dynamodb/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - curso-avanzado-serverless-framework-aws:/home/dynamodblocal/db

volumes:
  curso-avanzado-serverless-framework-aws:
    driver: local
